version: "3"

services:
  api:
    build: ./api
    depends_on:
      - mongo
    networks:
      - default

  client:
    build: ./test_client
    command: sh -c "sleep 7 && npm start"
    depends_on:
      - api
    networks:
      - default

  mongo:
    image: mongo:latest
    command: mongod --replSet rs0 --bind_ip_all --oplogSize 8
    environment:
      MONGO_INITDB_REPLICA_SET_NAME: rs0
      MONGO_INITDB_ENABLE_CLUSTER_AUTH: "false"
networks:
  default:
